export const DB_PROVIDER_TOKEN = Symbol('DB_PROVIDER_TOKEN');

export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const AUTH_TOKEN_REPOSITORY = Symbol('AUTH_TOKEN_REPOSITORY');
export const BLOG_REPOSITORY = Symbol('BLOG_REPOSITORY');
export const NOTE_REPOSITORY = Symbol('NOTE_REPOSITORY');
export const COMMENT_REPOSITORY = Symbol('COMMENT_REPOSITORY');
export const LIKE_REPOSITORY = Symbol('LIKE_REPOSITORY');
export const BOOKMARK_REPOSITORY = Symbol('BOOKMARK_REPOSITORY');
export const NEWSLETTER_REPOSITORY = Symbol('NEWSLETTER_REPOSITORY');
export const ANALYTICS_REPOSITORY = Symbol('ANALYTICS_REPOSITORY');
export const ADMIN_REPOSITORY = Symbol('ADMIN_REPOSITORY');
export const SEARCH_REPOSITORY = Symbol('SEARCH_REPOSITORY');
export const HEALTH_REPOSITORY = Symbol('HEALTH_REPOSITORY');

/** Internal adapters — not injected by feature services */
export const USER_REPOSITORY_PG = Symbol('USER_REPOSITORY_PG');
export const USER_REPOSITORY_MONGO = Symbol('USER_REPOSITORY_MONGO');
export const AUTH_TOKEN_REPOSITORY_PG = Symbol('AUTH_TOKEN_REPOSITORY_PG');
export const AUTH_TOKEN_REPOSITORY_MONGO = Symbol('AUTH_TOKEN_REPOSITORY_MONGO');
export const BLOG_REPOSITORY_PG = Symbol('BLOG_REPOSITORY_PG');
export const BLOG_REPOSITORY_MONGO = Symbol('BLOG_REPOSITORY_MONGO');
export const NOTE_REPOSITORY_PG = Symbol('NOTE_REPOSITORY_PG');
export const NOTE_REPOSITORY_MONGO = Symbol('NOTE_REPOSITORY_MONGO');
export const COMMENT_REPOSITORY_PG = Symbol('COMMENT_REPOSITORY_PG');
export const COMMENT_REPOSITORY_MONGO = Symbol('COMMENT_REPOSITORY_MONGO');
export const LIKE_REPOSITORY_PG = Symbol('LIKE_REPOSITORY_PG');
export const LIKE_REPOSITORY_MONGO = Symbol('LIKE_REPOSITORY_MONGO');
export const BOOKMARK_REPOSITORY_PG = Symbol('BOOKMARK_REPOSITORY_PG');
export const BOOKMARK_REPOSITORY_MONGO = Symbol('BOOKMARK_REPOSITORY_MONGO');
export const NEWSLETTER_REPOSITORY_PG = Symbol('NEWSLETTER_REPOSITORY_PG');
export const NEWSLETTER_REPOSITORY_MONGO = Symbol('NEWSLETTER_REPOSITORY_MONGO');
export const ANALYTICS_REPOSITORY_PG = Symbol('ANALYTICS_REPOSITORY_PG');
export const ANALYTICS_REPOSITORY_MONGO = Symbol('ANALYTICS_REPOSITORY_MONGO');
export const ADMIN_REPOSITORY_PG = Symbol('ADMIN_REPOSITORY_PG');
export const ADMIN_REPOSITORY_MONGO = Symbol('ADMIN_REPOSITORY_MONGO');
export const SEARCH_REPOSITORY_PG = Symbol('SEARCH_REPOSITORY_PG');
export const SEARCH_REPOSITORY_MONGO = Symbol('SEARCH_REPOSITORY_MONGO');
export const HEALTH_REPOSITORY_PG = Symbol('HEALTH_REPOSITORY_PG');
export const HEALTH_REPOSITORY_MONGO = Symbol('HEALTH_REPOSITORY_MONGO');

export const DATABASE_REPOSITORY_TOKENS = [
  USER_REPOSITORY,
  AUTH_TOKEN_REPOSITORY,
  BLOG_REPOSITORY,
  NOTE_REPOSITORY,
  COMMENT_REPOSITORY,
  LIKE_REPOSITORY,
  BOOKMARK_REPOSITORY,
  NEWSLETTER_REPOSITORY,
  ANALYTICS_REPOSITORY,
  ADMIN_REPOSITORY,
  SEARCH_REPOSITORY,
  HEALTH_REPOSITORY,
] as const;
