export const DB_PROVIDER_TOKEN = Symbol('DB_PROVIDER_TOKEN');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const AUTH_TOKEN_REPOSITORY = Symbol('AUTH_TOKEN_REPOSITORY');
export const BLOG_REPOSITORY = Symbol('BLOG_REPOSITORY');
export const NOTE_REPOSITORY = Symbol('NOTE_REPOSITORY');
export const COMMENT_REPOSITORY = Symbol('COMMENT_REPOSITORY');
export const LIKE_REPOSITORY = Symbol('LIKE_REPOSITORY');
export const BOOKMARK_REPOSITORY = Symbol('BOOKMARK_REPOSITORY');
export const NEWSLETTER_REPOSITORY = Symbol('NEWSLETTER_REPOSITORY');
export const ANALYTICS_REPOSITORY = Symbol('ANALYTICS_REPOSITORY');
export const ADMIN_REPOSITORY = Symbol('ADMIN_REPOSITORY');
export const SEARCH_REPOSITORY = Symbol('SEARCH_REPOSITORY');
export const HEALTH_REPOSITORY = Symbol('HEALTH_REPOSITORY');

export const DATABASE_REPOSITORY_TOKENS = [
  USER_REPOSITORY,
  AUTH_TOKEN_REPOSITORY,
  BLOG_REPOSITORY,
  NOTE_REPOSITORY,
  COMMENT_REPOSITORY,
  LIKE_REPOSITORY,
  BOOKMARK_REPOSITORY,
  NEWSLETTER_REPOSITORY,
  ANALYTICS_REPOSITORY,
  ADMIN_REPOSITORY,
  SEARCH_REPOSITORY,
  HEALTH_REPOSITORY,
] as const;
